baseurl = "/"
title = "Academic"
copyright = "&copy; 2018"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
disqusShortname = ""
googleAnalytics = ""
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = true  
  fractions = true  
  smartypants = true 

[params]
  color_theme = "default"
  font = "default"
  name = "Lena Smith"
  role = "Professor of Artificial Intelligence"
  organizations = [ { name = "Stanford University", url = "" } ]
  gravatar = false
  avatar = "portrait.jpg" 
  email = "test@example.org"
  address = "Building 1 Room 1, Stanford University, California, 90210, USA"
  office_hours = "Monday 10:00 to 13:00 or email for appointment"
  phone = "888 888 88 88"
  skype = "echo123"
  telegram = ""
  keybase = ""
  logo = ""
  map = 0
  map_api_key = ""
  latitude = "37.4275"
  longitude = "-122.1697"
  zoom = 15
  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"
  reading_time = true
  comment_count = true
  section_pager = false
  math = false
  highlight = true
  highlight_languages = []
  highlight_style = "github"
  sharing = true
  privacy_pack = false
  custom_css = []
  custom_js  = []
  publication_types = [
    'Uncategorized', 
    'Conference paper', 
    'Journal article',  
    'Manuscript',  
    'Report', 
    'Book',  
    'Book section' 
  ]

  [params.talks]
    time = true

  [params.publications]
    date_format = "January, 2006"

  [params.projects]
    list_children = true
    publication_format = 3

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:test@example.org"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/GeorgeCushen"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/gcushen"

  [params.menus]
    # Align the main menu to the right of the page? (true/false)
    align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  
[Languages.en]
  languageCode = "en-us"
