baseurl = "/"
title = "Academic"
copyright = "&copy; 2018"
theme = "academic"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10.0
disqusShortname = "a"
googleAnalytics = "a"
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
home = ["HTML", "CSS", "RSS"]
section = ["HTML", "RSS"]

[blackfriday]
fractions = true
hrefTargetBlank = true
smartypants = true

[params]
address = "Building 1 Room 1, Stanford University, California, 90210, USA"
avatar = "portrait.jpg"
color_theme = "default"
email = "test@example.org"
font = "default"
gravatar = false
keybase = ""
latitude = "37.4275"
logo = ""
longitude = "-122.1697"
map = 0.0
map_api_key = ""
name = "Lena Smith"
office_hours = "Monday 10:00 to 13:00 or email for appointment"
phone = "888 888 88 88"
role = "Professor of Artificial Intelligence"
skype = "echo123"
telegram = ""
zoom = 15.0

[[params.organizations]]
name = "Stanford University"
url = ""