baseurl = "/"
title = "Academic"
copyright = "&copy; 2018"
theme = "academic"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10.0
disqusShortname = ""
googleAnalytics = ""
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
home = ["HTML", "CSS", "RSS"]
section = ["HTML", "RSS"]

[blackfriday]
fractions = true
hrefTargetBlank = true
smartypants = true

[params]
color_theme = "default"
publication_types = ["Uncategorized", "Conference paper", "Journal article", "Manuscript", "Report", "Book", "Book section"]

[params.menus]
align_right = true

[params.projects]
list_children = true
publication_format = 3.0

[[params.social]]
icon = "envelope"
icon_pack = "fa"
link = "mailto:test@example.org"

[[params.social]]
icon = "twitter"
icon_pack = "fa"
link = "//twitter.com/GeorgeCushen"

[[params.social]]
icon = "google-scholar"
icon_pack = "ai"
link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

[[params.social]]
icon = "github"
icon_pack = "fa"
link = "//github.com/gcushen"

[params.talks]
time = true

[Languages]

[Languages.en]
languageCode = "en-us"