backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads" # Media files will be stored in the repo under static/img/uploads
public_folder: "/uploads" 


publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog post"
    folder: "content/post/"
    create: true
    fields:
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Modification Date", name: "lastmod", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Summary", name: "summary" }
      - { label: "Description", name: "description", widget: "markdown", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["academic"] }
      - {label: "Header", name: header, widget: object, fields: [
              {label: "Featured Image", name: "image", widget: "image", required: false},
              {label: "Caption", name: "caption", widget: string}]}
