backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/" # Media files will be stored in the repo under static/img/uploads
public_folder: "/img"

collections:

  # PAGE SECTIONS

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/home/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: Widget, name: widget, widget: string, default: "about"}
          - {label: Widget, name: widget,  default: 5}
          - {label: "Interests", name: interests, widget: object, fields: [
              {label: "Interests list", name: "interests", widget: "list", 
              default: ["Artificial Intelligence"]}]}
          - label: "Education"
              name: "education"
              widget: "object"
              fields:
                - label: "courses"
                  name: "courses"
                  widget: "list"
                  fields:
                    - {label: Course, name: course , widget: string}
                    - {label: Institution, name: avatar, widget: string}
                    - {label: Year, name: year, widget: number}
          - { label: "Body", name: "body", widget: "markdown", required: false }

  # POSTS

  - name: "blog"
    label: "Blog post"
    folder: "content/post/"
    create: true
    fields:
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Modification Date", name: "lastmod", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Tags", name: "tags", widget: "list", default: ["academic"] }
      - { label: "Summary", name: "summary" }
      - { label: "Header", name: header, widget: object, fields: [
              {label: "Featured Image", name: "image", widget: "image", required: false},
              {label: "Caption", name: "caption", widget: string}]}
      - { label: "Body", name: "body", widget: "markdown", required: false }

  # PUBLICATIONS

  - name: "publication"
    label: "Publication"
    folder: "content/publication/"
    create: true
    fields:
      - { label: "Title", name: "title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Authors", name: "authors", widget: "list"}
      - { label: "Publication type, (Uncategorized:0,Conference:1,Journal:2,WIP:3,TechReport:4,Book:5,BookChpt:6)" 
             ,name: "publication_types", widget: "list", default: ['0', '1']}
      - {label: "Header", name: header, widget: object, fields: [
              {label: "Featured Image", name: "image", widget: "image", required: false},
              {label: "Caption", name: "caption", widget: string}]}
      - { label: "Publication Name", name: "publication" }
      - { label: "Publication Name short", name: "publication_short" }
      - { label: "Abstract", name: "abstract" }
      - { label: "Abstract short", name: "abstract_short" }
      - { label: "Image preview", name: "image_preview", widget: "image", required: false }
      - { label: "Selected publication?", name: "selected", widget: "boolean", default: true }
      - { label: "Url pdf", name: "url_pdf"}
      - { label: "Url preprint", name: "url_preprint"}
      - { label: "Url dataset", name: "url_dataset"}
      - { label: "Url project", name: "url_project"}
      - { label: "Url slides", name: "url_slides"}
      - { label: "Url video", name: "url_video"}
      - { label: "Url poster", name: "url_poster"}
      - { label: "Url source", name: "url_source"}
      - { label: "USE MATH formatting?", name: "math", widget: "boolean", default: true }
      - { label: "USE Source code highlighting?", name: "math", widget: "boolean", default: true } 
      - { label: "Body", name: "body", widget: "markdown", required: false }


  # PROJECTS

  - name: "project"
    label: "Project"
    folder: "content/project/"
    create: true
    fields:
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title" }
      - { label: "Summary", name: "summary"}
      - { label: "Image preview", name: "image_preview", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["academic"] }
      - { label: "External link, Optional external URL for project (replaces project detail page)", name: "external_link", required: false}
      - { label: "USE MATH formatting?", name: "math", widget: "boolean", default: false }
      - { label: "Header", name: header, widget: object, fields: [
              {label: "Featured Image", name: "image", widget: "image", required: false},
              {label: "Caption", name: "caption", widget: string}]}
      - { label: "Body", name: "body", widget: "markdown", required: false }


  # TALK

  - name: "talk"
    label: "Talk"
    folder: "content/talk/"
    create: true
    fields:
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title" ,widget: string}
      - { label: "Time start", name: "time_start", widget: "datetime" }
      - { label: "Time end", name: "time_end", widget: "datetime" }
      - { label: "Abstract", name: "abstract",widget: string}
      - { label: "Abstract short", name: "abstract_short",widget: string}
      - { label: "Event", name: "event",widget: string}
      - { label: "Event URL", name: "event url",widget: string}
      - { label: "Location (City, Country)", name: "location",widget: string}
      - { label: "Selected talk?", name: "selected", widget: "boolean", default: false }
      - { label: "Projects (Simply enter the filename (excluding '.md') of your project file in `content/project/`)", name: "projects", widget: "list", default: [] ,required: false}
      - { label: "USE MATH formatting?", name: "math", widget: "boolean", default: false }
      - { label: "PDF URL", name: "url_pdf",widget: string}
      - { label: "Slides URL", name: "url_slides",widget: string}
      - { label: "Video URL", name: "url_video",widget: string}
      - { label: "Source code URL", name: "url_code",widget: string}
      - { label: "USE Source code highlighting?", name: "math", widget: "boolean", default: true } 
      - { label: "Header", name: header, widget: object, fields: [
              {label: "Featured Image", name: "image", widget: "image", required: false},
              {label: "Caption", name: "caption", widget: string}]}
      - { label: "Body", name: "body", widget: "markdown", required: false }

      
